//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F1_EF_DF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPilot
    {
        public int IdCar { get; set; }
        public int IdPilot { get; set; }
        public System.DateTime EventDate { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Pilot Pilot { get; set; }
        public override string ToString()
        {
            return "\nId Carro: " + this.IdCar+"\nId Piloto: "+this.IdPilot +"\nData Evento: "+this.EventDate;
        }
    }
}
